
/**************************************************************
 *	
 *	battlemusic2, 8 bit, 11025Hz,
 *	1 channel, 3289248 bytes/channel
 *	Total Size: 1 * 3289248 + 4 (header) = 3289292 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\abies\Documents\School\CS 2261\SmashLite_AbieshekSubramaniam\battlemusic2.wav
 *	Time-stamp: Mon Apr 27 03:38:40 2020
 *	
 **************************************************************/

#ifndef __BATTLEMUSIC2H__
#define __BATTLEMUSIC2H__

#define BATTLEMUSIC2FREQ 11025
#define BATTLEMUSIC2LEN 3289248

extern const unsigned char battlemusic2[3289248];

#endif /* __BATTLEMUSIC2H__ */
