
/**************************************************************
 *	
 *	battlemusic, 8 bit, 11025Hz,
 *	1 channel, 1427904 bytes/channel
 *	Total Size: 1 * 1427904 + 4 (header) = 1427948 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\abies\Documents\School\CS 2261\SmashLite_AbieshekSubramaniam\battlemusic.wav
 *	Time-stamp: Sun Apr 19 02:37:55 2020
 *	
 **************************************************************/

#ifndef __BATTLEMUSICH__
#define __BATTLEMUSICH__

#define BATTLEMUSICFREQ 11025
#define BATTLEMUSICLEN 1427904

extern const unsigned char battlemusic[1427904];

#endif /* __BATTLEMUSICH__ */
