
/**************************************************************
 *	
 *	blocksound, 8 bit, 11025Hz,
 *	1 channel, 2829 bytes/channel
 *	Total Size: 1 * 2829 + 4 (header) = 2873 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\abies\Documents\School\CS 2261\SmashLite_AbieshekSubramaniam\blocksound.wav
 *	Time-stamp: Sun Apr 19 03:25:13 2020
 *	
 **************************************************************/

#ifndef __BLOCKSOUNDH__
#define __BLOCKSOUNDH__

#define BLOCKSOUNDFREQ 11025
#define BLOCKSOUNDLEN 2829

extern const unsigned char blocksound[2829];

#endif /* __BLOCKSOUNDH__ */
