
/**************************************************************
 *	
 *	bossdeathsound, 8 bit, 11025Hz,
 *	1 channel, 49824 bytes/channel
 *	Total Size: 1 * 49824 + 4 (header) = 49868 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\abies\Documents\School\CS 2261\SmashLite_AbieshekSubramaniam\bossdeathsound.wav
 *	Time-stamp: Sun Apr 19 03:01:33 2020
 *	
 **************************************************************/

#ifndef __BOSSDEATHSOUNDH__
#define __BOSSDEATHSOUNDH__

#define BOSSDEATHSOUNDFREQ 11025
#define BOSSDEATHSOUNDLEN 49824

extern const unsigned char bossdeathsound[49824];

#endif /* __BOSSDEATHSOUNDH__ */
