
/**************************************************************
 *	
 *	damagesound, 8 bit, 11025Hz,
 *	1 channel, 6132 bytes/channel
 *	Total Size: 1 * 6132 + 4 (header) = 6176 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\abies\Documents\School\CS 2261\SmashLite_AbieshekSubramaniam\damagesound.wav
 *	Time-stamp: Sun Apr 19 03:25:06 2020
 *	
 **************************************************************/

#ifndef __DAMAGESOUNDH__
#define __DAMAGESOUNDH__

#define DAMAGESOUNDFREQ 11025
#define DAMAGESOUNDLEN 6132

extern const unsigned char damagesound[6132];

#endif /* __DAMAGESOUNDH__ */
