
/**************************************************************
 *	
 *	defeatmusic, 8 bit, 11025Hz,
 *	1 channel, 4843584 bytes/channel
 *	Total Size: 1 * 4843584 + 4 (header) = 4843628 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\abies\Documents\School\CS 2261\SmashLite_AbieshekSubramaniam\defeatmusic.wav
 *	Time-stamp: Sun Apr 19 03:01:48 2020
 *	
 **************************************************************/

#ifndef __DEFEATMUSICH__
#define __DEFEATMUSICH__

#define DEFEATMUSICFREQ 11025
#define DEFEATMUSICLEN 4843584

extern const unsigned char defeatmusic[4843584];

#endif /* __DEFEATMUSICH__ */
