
/**************************************************************
 *	
 *	jumpsound, 8 bit, 11025Hz,
 *	1 channel, 8470 bytes/channel
 *	Total Size: 1 * 8470 + 4 (header) = 8514 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\abies\Documents\School\CS 2261\SmashLite_AbieshekSubramaniam\jumpsound.wav
 *	Time-stamp: Sun Apr 19 03:25:00 2020
 *	
 **************************************************************/

#ifndef __JUMPSOUNDH__
#define __JUMPSOUNDH__

#define JUMPSOUNDFREQ 11025
#define JUMPSOUNDLEN 8470

extern const unsigned char jumpsound[8470];

#endif /* __JUMPSOUNDH__ */
