
/**************************************************************
 *	
 *	openingmusic, 8 bit, 11025Hz,
 *	1 channel, 1346400 bytes/channel
 *	Total Size: 1 * 1346400 + 4 (header) = 1346444 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\abies\Documents\School\CS 2261\SmashLite_AbieshekSubramaniam\openingmusic.wav
 *	Time-stamp: Wed Apr 22 20:35:01 2020
 *	
 **************************************************************/

#ifndef __OPENINGMUSICH__
#define __OPENINGMUSICH__

#define OPENINGMUSICFREQ 11025
#define OPENINGMUSICLEN 1346400

extern const unsigned char openingmusic[1346400];

#endif /* __OPENINGMUSICH__ */
