
/**************************************************************
 *	
 *	runsound, 8 bit, 11025Hz,
 *	1 channel, 24705 bytes/channel
 *	Total Size: 1 * 24705 + 4 (header) = 24749 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\abies\Documents\School\CS 2261\SmashLite_AbieshekSubramaniam\runsound.wav
 *	Time-stamp: Sun Apr 19 03:24:53 2020
 *	
 **************************************************************/

#ifndef __RUNSOUNDH__
#define __RUNSOUNDH__

#define RUNSOUNDFREQ 11025
#define RUNSOUNDLEN 24705

extern const unsigned char runsound[24705];

#endif /* __RUNSOUNDH__ */
