
/**************************************************************
 *	
 *	startsound, 8 bit, 11025Hz,
 *	1 channel, 11747 bytes/channel
 *	Total Size: 1 * 11747 + 4 (header) = 11791 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\abies\Documents\School\CS 2261\SmashLite_AbieshekSubramaniam\startsound.wav
 *	Time-stamp: Wed Apr 22 21:10:27 2020
 *	
 **************************************************************/

#ifndef __STARTSOUNDH__
#define __STARTSOUNDH__

#define STARTSOUNDFREQ 11025
#define STARTSOUNDLEN 11747

extern const unsigned char startsound[11747];

#endif /* __STARTSOUNDH__ */
