
/**************************************************************
 *	
 *	swordsound, 8 bit, 11025Hz,
 *	1 channel, 9428 bytes/channel
 *	Total Size: 1 * 9428 + 4 (header) = 9472 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\abies\Documents\School\CS 2261\SmashLite_AbieshekSubramaniam\swordsound.wav
 *	Time-stamp: Sun Apr 19 03:24:40 2020
 *	
 **************************************************************/

#ifndef __SWORDSOUNDH__
#define __SWORDSOUNDH__

#define SWORDSOUNDFREQ 11025
#define SWORDSOUNDLEN 9428

extern const unsigned char swordsound[9428];

#endif /* __SWORDSOUNDH__ */
