
/**************************************************************
 *	
 *	victorymusic, 8 bit, 11025Hz,
 *	1 channel, 596736 bytes/channel
 *	Total Size: 1 * 596736 + 4 (header) = 596780 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\abies\Documents\School\CS 2261\SmashLite_AbieshekSubramaniam\victorymusic.wav
 *	Time-stamp: Sun Apr 19 03:02:41 2020
 *	
 **************************************************************/

#ifndef __VICTORYMUSICH__
#define __VICTORYMUSICH__

#define VICTORYMUSICFREQ 11025
#define VICTORYMUSICLEN 596736

extern const unsigned char victorymusic[596736];

#endif /* __VICTORYMUSICH__ */
